emaillogin/emaillogin/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('verify_app.urls'))
]

emaillogin/verify_app/urls.py
from django.urls import path
from . import views
app_name ='verify_app'
urlpatterns = [

    path('login/',views.user_login,name='login'),
    path('register/', views.register, name='register'),
    path("logout/", views.logout_request, name="logout"),
]

emaillogin/verify_app/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models
from django.utils.translation import ugettext_lazy as _

class UserManager(BaseUserManager):
    """Define a model manager for User model with no username field."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """Create and save a User with the given email and password."""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """Create and save a regular User with the given email and password."""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)



class User(AbstractUser):
    # User model.

    username = None
    email = models.EmailField(_('email address'), unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    objects = UserManager()

emaillogin/verify_app/forms.py
from django import forms

from .models import User


class LoginForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)

class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password',widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password',widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ( 'first_name', 'last_name', 'email')
    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']

emaillogin/verify_app/views.py
from django.contrib import messages
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .forms import LoginForm,UserRegistrationForm

def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request,
                                        email=cd['email'],
                                        password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request,user)
                    return render(request, 'verify_app/login_done.html')
                else:
                    return HttpResponse('Disabled account')
            else:
                return HttpResponse('Invalid login')
    else:
        form = LoginForm()
    return render(request, 'verify_app/login.html', {'form': form})

def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            # Create a new user object but avoid saving it yet
            new_user = user_form.save(commit=False)
            # Set the chosen password
            new_user.set_password(user_form.cleaned_data['password'])
            # Save the User object
            new_user.save()
            return render(request,'verify_app/register_done.html',{'new_user': new_user})
    else:
        user_form = UserRegistrationForm()
    return render(request,'verify_app/register.html',{'user_form': user_form})


def logout_request(request):
    logout(request)
    messages.info(request, "Logged out successfully!")
    return redirect("verify_app:login")

emaillogin/verify_app/templates/verify_app/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
        <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>{%block title %}{% endblock %}</title>
  </head>
<body>
    <div class="container">
        <div class="jumbotron">
    {% block body %} {% endblock %}
        </div>
    </div>
</body>
</html>

emaillogin/verify_app/templates/verify_app/login.html
{% extends 'verify_app/base.html' %}

{% block head %}
    {% block title %}Login{% endblock %}
{% endblock %}
{% block body %}
            <h1>Login Here...........</h1><br>
                <form action="." method="post">
                    {{ form.as_p }}
                    {% csrf_token %}
                    <input type="submit"class=" bg-primary text-white" value="login">
                </form>
{% endblock %}

emaillogin/verify_app/templates/verify_app/login_done.html
{% extends 'verify_app/base.html' %}
{% block head %}
        {% block title %}login_done{% endblock %}
{% endblock %}

{% block body %}
        <h1>Welcome {{ new_user.first_name }}!</h1>
<p>Your are successfully logged in.<b>For <a href="{% url 'verify_app:logout' %}">logout</a> click on tha  logout link</b></p>

{% endblock %}

emaillogin/verify_app/templates/verify_app/register.html
{% extends 'verify_app/base.html' %}
{% block head %}
    {% block title %}Register{% endblock %}
{% endblock %}
{% block body %}
            <h1>Create an account</h1>
            <p>Please, sign up using the following form:</p>
                <form action="." method="post">
                    {{ user_form.as_p }}
                    {% csrf_token %}
                    <p><input type="submit" class=" bg-primary text-white" value="Create my account"></p>
                </form>

{% endblock %}

emaillogin/verify_app/templates/verify_app/register_done.html
{% extends 'verify_app/base.html' %}
{% block head %}
        {% block title %}Register_done{% endblock %}
{% endblock %}

{% block body %}
        <h1>Welcome {{ new_user.first_name }}!</h1>
        <p>Your account has been successfully created.</p>
        <p>For <a href="{% url 'verify_app:login' %}">login</a> click on link.</p>

{% endblock %}